BTL/Controllers/ManagerController.cs
using BTL.DTO;
using BTL.Models;
using Microsoft.AspNetCore.Mvc;
using X.PagedList;

namespace BTL.Controllers
{
    public class ManagerController : Controller
    {
        private readonly ILogger<ManagerController> _logger;
        private DictionaryContext _dBDic { get; set; }
        public ManagerController(ILogger<ManagerController> logger, DictionaryContext dictionaryContext)
        {
            _logger = logger;
            this._dBDic = dictionaryContext;
        }
        //------------------------MANAGER/WORD---------------------------
        [HttpGet]
        [Route("/manager/word")]
        public IActionResult Index(int page = 1)
        {
            int pageSize = 10;
            int pageNumber = page;
            PagedList<TblWord> word = new PagedList<TblWord>(this._dBDic.getallword().ToList(), pageNumber, pageSize);
            return View("Index", word);
        }
        [HttpPost]
        [Route("/manager/word")]
        public IActionResult getwordbyWord(string Word, int page = 1)
        {
            int pageSize = 10;
            int pageNumber = page;
            PagedList<TblWord> word = new(this._dBDic.searchword(Word).ToList(), pageNumber, pageSize);
            return View("Index", word);
        }
        [HttpPost]
        [Route("/manager/word/edit")]
        public IActionResult editword([FromBody] TblWord data)
        {
            this._dBDic.editword(data.Id, data.IdLanguage, data.IdLanguageTrans, data.IdWordtype, data.IdUser, data.SWord, data.SExample, data.SDefinition, data.sWordTrans);
            return Json(data);
        }
        [HttpGet]
        [Route("manager/searchWord")]
        public List<WordSearch> searchWords(int Id_Language, int Id_Language_trans, string sWord)
        {
            List<WordSearch> w = this._dBDic.searchWord(Id_Language, Id_Language_trans, sWord).ToList();
            return w;
        }
        [HttpDelete]
        [Route("/manager/word/delete")]
        public IActionResult DeleteWord([FromBody] TblWord data)
        {
            this._dBDic.deleteWord(data.Id);
            return Json(data);
        }
        //--------------------------MANAGER/USER----------------------------

        [HttpGet]
		[Route("/manager/user")]
        public IActionResult ManagerUser(int page = 1)
        {
            int pageSize = 10;
            int pageNumber = page;
            PagedList<TblUser> users = new PagedList<TblUser>(this._dBDic.getAllUser().ToList(), pageNumber, pageSize);
            return View("managerUser", users);
        }




        [HttpPost]
        [Route("/manager/user/upgrade")]
        public IActionResult UpGradeUserRole([FromBody] TblUser data)
        {
            this._dBDic.UpgradeRoleUser(data.Id, data.SRole);
            return Json(data);
        }


        [HttpDelete]
        [Route("/manager/user/delete")]
        public IActionResult deleteUser([FromBody] TblUser data)
        {
            this._dBDic.deleteUser(data.Id);
            return Json(data);
        }

        [HttpGet]
        [Route("/manager/user/filterUser")]
        public IActionResult filterUser(string email="", string role="", int page = 1)
        {
            Console.WriteLine("áda "+email + role);
            int pageSize = 10;
            int pageNumber = page;
            PagedList<TblUser> userFilter = new PagedList<TblUser>(this._dBDic.filterUser(email, role).ToList(), pageNumber, pageSize);
            return View("managerUser", userFilter);
        }


        [HttpGet]
        [Route("/manager/user/getListPageAjax")]
        public ActionResult getListPageAjax(int page=1, int pageSize=1)
        {
            List<TblUser> users = this._dBDic.getAllUser().ToList(); ;

            var pageIndex = page;
            var totalPage= users.Count;
            var numberPage = Math.Ceiling((float)(totalPage / pageSize));
            var start = (pageIndex - 1) * pageSize;
            var users1 = users.Skip(start).Take(pageSize);

            return Json(new
            {
                data = users1,
                totalItem = users.Count,
                page,
                pageSize
            });
        }
    }
}

BTL/Views/Manager/managerUser.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
	ViewData["Title"] = "Manager User Page";
}
@using X.PagedList.Mvc.Core
@model X.PagedList.IPagedList<TblUser>


<form asp-action="filterUser" asp-controller="Manager" method="get" class="flex items-center gap-3">
    
    <input name="email" placeholder="Email search"/>
    <label for="role">Role</label>
    <select id="role" name="role" class="bg-gray-50 border border-gray-300 text-gray-900 text-xl w-fit lg:text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block p-2.5 ">
        <option value="" selected>Tất cả</option>
        <option value="User">User</option>
        <option value="CTV">CTV</option>
    </select>
    <input type="submit" value="Search" class="bg-blue-700 text-white w-[65px] h-[30px] rounded-3 hover:opacity-75"/>
    <a href="/manager/user" class="bg-red-700 text-white  px-[10px] py-[3px]  rounded-3 hover:opacity-75 hover:text-black">Cancel</a>
</form>
<div class="relative overflow-x-auto shadow-md sm:rounded-lg mt-12">
    <table class="w-full text-sm text-left rtl:text-right text-gray-500">
        <thead class="text-xs text-gray-700 uppercase bg-gray-200 ">
            <tr>
                <th scope="col" class="px-6 py-3 w-[50px]">
                    ID
                </th>
                <th scope="col" class="px-6 py-3">
                   Email
                </th>
                <th scope="col" class="px-6 py-3 w-[120px]">
                    Role
                </th>
                <th scope="col" class="px-6 py-3 w-[200px]">
                    Action
                </th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Count >0)
            {
                @foreach (TblUser user in Model)
                {
                    <tr class="border-b dark:border-gray-700">
                        <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap ">
                            @user.Id
                        </th>
                        <td class="px-6 py-4">
                            @user.SEmail
                        </td>
                        <td class="px-6 py-4">
                            @user.SRole
                        </td>
                        <td class="px-6 py-4 flex flex-col">
                            @if (@user.SRole == "CTV")
                            {
                                <a id="toUser" onclick="upgradeRole(@user.Id,'User')" class="cursor-pointer font-medium text-blue-600 dark:text-blue-500 hover:underline">To normal User</a>

                            }
                            @if (@user.SRole == "User")
                            {
                                <a id="updateToCTV" onclick="upgradeRole(@user.Id,'CTV')" class="cursor-pointer font-medium text-blue-600 dark:text-blue-500 hover:underline">To CTV</a>
                            }
                            <a onclick="openModal(event)" data-id="@user.Id" class="cursor-pointer font-medium text-blue-600 dark:text-blue-500 hover:underline">Delete</a>

                        </td>
                    </tr>
                    
                }

                <div id="popup-modal" tabindex="-1" onclick="openModal(event)" class="h-full bg-[rgba(136,139,147,0.5)] hidden flex justify-center items-baseline overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-[calc(100%-1rem)] max-h-full">
                    <div class="relative p-4 w-full max-w-md max-h-full">
                        <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
                            <button onclick="openModal(event)" type="button" class="absolute top-3 end-2.5 text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ms-auto inline-flex justify-center items-center" data-modal-hide="popup-modal">
                                <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
                                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6" />
                                </svg>
                                <span class="sr-only">Close modal</span>
                            </button>
                            <div class="p-4 md:p-5 text-center">
                                <svg class="mx-auto mb-4 text-gray-400 w-12 h-12 dark:text-gray-200" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 11V6m0 8h.01M19 10a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
                                </svg>
                                <h3 class="mb-5 text-lg font-normal text-gray-500 dark:text-gray-400">Bạn có chắc chắn muốn xóa User này?</h3>
                                <div class="flex justify-content-around">
                                    <button onclick="deleteUser(event)" data-modal-hide="popup-modal" type="button" class="text-white bg-red-600 hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300 font-medium rounded-lg text-sm inline-flex items-center px-4 py-2.5 text-center">
                                        Có, tôi chắc chắn
                                    </button>
                                    <button onclick="openModal(event)" data-modal-hide="popup-modal" type="button" class="py-2.5 px-4 ms-3 text-sm font-medium text-gray-900 focus:outline-none bg-white rounded-lg border border-gray-200 hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-4 focus:ring-gray-100 ">Không, thoát</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }
           

            @if (Model.Count == 0)
            {
                <tr class="h-[300px]">
                    <td colspan="4" class="text-center font-[500] text-[20px]">Không có User nào</td>
                </tr>
            }
           
        </tbody>
    </table>
</div>

@Html.PagedListPager(Model, page => Url.Action("ManagerUser", new { page = page }))